### PR TITLE
Specify a character set

### PR DESCRIPTION
**Pull request by pathawks**
`text/html` Files should have the character set specified in the type header. `text/html; charset=utf-8`

Perhaps this would fit better in [mojombo/jekyll](https://github.com/mojombo/jekyll), I'm not sure.

### CODE REVIEW

**Comment by laurilehmijoki** [comment]
Can you amend this pull request with new tests that specify this feature? 

Moreover, currently this pull request breaks some of existing tests. As a result, I cannot yet accept this.

**Comment by pathawks** [comment]
> Can you amend this pull request with new tests that specify this feature?

Oh, I don't know where to begin; I'm not really a Ruby guy.  
I'll do my best if you can point me in the direction of how to get started.

**Comment by laurilehmijoki** [comment]
You can take a look at the tests that are already in this project.

Your implementation is fine. I'd like to merge it, but unfortunately I don't right now have the time to write the specs for it.

**Comment by laurilehmijoki** [comment]
Released in 3.0.0.

**Pull request closed without merging**
